In [3]:
import pandas as pd
import geopandas as gpd
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.15f' % x)  # Exibe 5 casas decimais

In [ ]:
sectors = gpd.read_file('/Volumes/ssd/Doutorado/DATASET/IBGE/Setores Censitários/setores_censitarios_2022/br/setores_censitarios_pop_fcu_ibp.shp')
sectors

,CD_GEOCOD_,pop_2022,CD_FCU_202,IBP_prop,geometry
0,120001305000001,920,None,0.358328630255183,"POLYGON ((-67.04925 -10.07069, -67.04938 -10.0..."
1,120001305000002,354,None,1.177328187333547,"POLYGON ((-67.03937 -10.07846, -67.03897 -10.0..."
2,120001305000005,278,None,3.390423875986217,"POLYGON ((-67.03598 -10.00512, -67.03653 -10.0..."
3,120001305000006,401,None,3.612239314456533,"POLYGON ((-66.91526 -9.86712, -66.91544 -9.867..."
4,120001305000007,241,None,2.835737148310999,"POLYGON ((-66.88699 -9.83206, -66.88808 -9.832..."
...,...,...,...,...,...
489073,172210705000030,276,17221070001,2.333801783211632,"POLYGON ((-48.53139 -6.41658, -48.53136 -6.416..."
489074,172210705000031,289,None,2.331757298862843,"POLYGON ((-48.52973 -6.41638, -48.52999 -6.416..."
489075,172210705000032,152,None,2.288070969094969,"POLYGON ((-48.53265 -6.41567, -48.53287 -6.415..."
489076,172210705000034,393,None,2.332797863853401,"POLYGON ((-48.53492 -6.41734, -48.53513 -6.417..."
489077,172210705000036,388,17221070001,2.332797863853400,"POLYGON ((-48.53205 -6.41989, -48.53202 -6.419..."

In [5]:
# join by CD_FCU_2022 calculating the mean of IBP_prop
# Group by CD_FCU_2022 and calculate mean IBP_prop, keeping geometry
fcu_ibp = setores.dissolve(by='CD_FCU_202', aggfunc={'IBP_prop': 'mean'}).reset_index()

# Drop rows where CD_FCU_202 is None since those aren't FCUs
fcu_ibp = fcu_ibp[fcu_ibp['CD_FCU_202'].notna()]

# Display result
fcu_ibp

,CD_FCU_202,geometry,IBP_prop
0,11000490002,"POLYGON ((-61.44456 -11.42432, -61.44547 -11.4...",-1.190800020270165
1,11000490006,"POLYGON ((-61.47698 -11.4123, -61.47698 -11.41...",1.348939830389360
2,11001060003,"POLYGON ((-65.31845 -10.79209, -65.3202 -10.79...",0.704954464215429
3,11001060004,"POLYGON ((-65.30695 -10.78101, -65.30775 -10.7...",2.122344372690510
4,11001060005,"POLYGON ((-65.29101 -10.76165, -65.29134 -10.7...",3.261340538797059
...,...,...,...
12343,53001080089,"POLYGON ((-48.04198 -15.77137, -48.04546 -15.7...",1.277365421646900
12344,53001080090,"POLYGON ((-47.66366 -15.64305, -47.66343 -15.6...",2.599055443227950
12345,53001080094,"POLYGON ((-48.0398 -15.87807, -48.04002 -15.87...",-0.129648558890625
12346,53001080095,"POLYGON ((-47.86696 -15.59219, -47.86721 -15.5...",1.065393206436609
12347,53001080096,"POLYGON ((-47.90935 -15.83957, -47.90952 -15.8...",-1.739138832075000

In [6]:
# save
fcu_ibp.to_file('/Volumes/ssd/Doutorado/DATASET/IBP - CIDACS/polygon/fcu_ibp.shp')