In [9]:
import pandas as pd
import geopandas as gpd
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.15f' % x)  # Exibe 5 casas decimais

# HOUSEHOLD LEVEL

## S.E.S (socio-economic status)

### Crowding

In [10]:
# Density - inhabitants per household
tabela9887_1 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/População/9887/tabela9887_dom_ocup.xlsx', skiprows=4, skipfooter=1)
tabela9887_2 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/População/9887/tabela9887_pop.xlsx', skiprows=4, skipfooter=1)

tabela9887_1 = tabela9887_1[['Unnamed: 0', 'Unnamed: 2']]
tabela9887_1.columns = ['CD_FCU', 'domicilios']
tabela9887_2 = tabela9887_2[['Unnamed: 0', 'Total']]
tabela9887_2.columns = ['CD_FCU', 'pessoas']

join = tabela9887_1.merge(tabela9887_2, on='CD_FCU', how='left')
join['hh_density'] = join['pessoas'] / join['domicilios']

final_table = join[['CD_FCU', 'hh_density']]

### Demographics

In [11]:

# Aging index of the resident population in slums and urban communities (Elderly: 60 years or older) (Ratio)
tabela9885_1 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/População/9885/tabela9885_1.xlsx', skiprows=0, skipfooter=0)
tabela9885_1 = tabela9885_1[['Unnamed: 0', 'Total']]
tabela9885_1.columns = ['CD_FCU', 'age_index']
final_table = final_table.merge(tabela9885_1, on='CD_FCU', how='left')

# Median age of the resident population in slums
tabela9885_2 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/População/9885/tabela9885_2.xlsx', skiprows=4, skipfooter=1)
tabela9885_2 = tabela9885_2[['Unnamed: 0', 'Total']]
tabela9885_2.columns = ['CD_FCU', 'median_age']
final_table = final_table.merge(tabela9885_2, on='CD_FCU', how='left')

# Sex ratio of the resident population in slums
tabela9884_2 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/População/9885/razao_sexo.xlsx', skiprows=4, skipfooter=1)
tabela9884_2 = tabela9884_2[['Unnamed: 0', 'Total']]
tabela9884_2.columns = ['CD_FCU', 'sex_ratio']
final_table = final_table.merge(tabela9884_2, on='CD_FCU', how='left')

In [12]:
final_table

            CD_FCU        hh_density          age_index  median_age  sex_ratio
0      11000490002 2.217391304347826 33.329999999999998          28         76
1      11000490006 2.795454545454545 32.030000000000001          29        111
2      11001060003 3.750000000000000 14.680000000000000          23         94
3      11001060004 3.455128205128205 21.510000000000002          25        115
4      11001060005 3.419354838709677 27.489999999999998          24        108
...            ...               ...                ...         ...        ...
12343  53001080089 3.186536901865369 22.710000000000001          30        101
12344  53001080090 2.815789473684211 14.020000000000000          26         96
12345  53001080094 2.991935483870968 18.520000000000000          25        111
12346  53001080095 2.926470588235294 25.100000000000001          27        105
12347  53001080096 3.133928571428572 47.439999999999998          32         96

[12348 rows x 5 columns]

### Education, literacy & training

In [13]:
# Literacy of the population aged 15 or older
tabela9886_2 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/População/9886/tabela9886_2_alfabetizacao.xlsx', skiprows=6, skipfooter=1)
tabela9886_2 = tabela9886_2[['Unnamed: 0', 'Total.1']]
tabela9886_2.columns = ['CD_FCU', 'literate']
# tabela9886_2['no_literate'] = 100 - tabela9886_2['demographic_literate']

final_table = final_table.merge(tabela9886_2, on='CD_FCU', how='left')

### Ethinicity and migration

In [14]:
# Resident population in slums by color or race (%)
tabela9884_2 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/População/9884/tabela9884_2_cor.xlsx', skiprows=6, skipfooter=1)
tabela9884_2 = tabela9884_2[['Unnamed: 0', 'Total.1', 'Total.2', 'Total.3', 'Total.4', 'Total.5', 'Total.6']]
tabela9884_2.columns = ['CD_FCU', 'race_wht', 'race_blk', 'race_ylw', 'race_brn', 'race_ind', 'race_unk']
final_table = final_table.merge(tabela9884_2, on='CD_FCU', how='left')

### Index of Deprivation

In [15]:
ibp = gpd.read_file('/Volumes/ssd/Doutorado/DATASET/IBP - CIDACS/polygon/fcu_ibp.shp')
ibp = ibp[['CD_FCU_202', 'IBP_prop']]
ibp.columns = ['CD_FCU', 'depriv_idx']
ibp['CD_FCU'] = ibp['CD_FCU'].astype(int)
final_table = final_table.merge(ibp, on='CD_FCU', how='left')

## Housing

### Property type

In [16]:
# Households in slums by type of occupation
tabela9887_2 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/População/9887/tabela9887_2.xlsx', skiprows=4, skipfooter=1)
tabela9887_2 = tabela9887_2[['Unnamed: 0', 'Particular', 'Coletivo']]
tabela9887_2.columns = ['CD_FCU', 'priv_hh', 'coll_hh']

final_table = final_table.merge(tabela9887_2, on='CD_FCU', how='left')

# Occupied permanent private households in slums by type of household 
tabela9890_2 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/Características dos Domicílios e dos Moradores/9890/tabela9890_2_domicilio.xlsx', skiprows=4, skipfooter=1)
tabela9890_2 = tabela9890_2[['Unnamed: 0', 'Casa', 'Casa de vila ou em condomínio', 'Apartamento', 'Habitação em casa de cômodos ou cortiço', 'Habitação indígena sem paredes ou maloca', 'Estrutura residencial permanente degradada ou inacabada']]
tabela9890_2.columns = ['CD_FCU', 'hh_type_1', 'hh_type_2', 'hh_type_3', 'hh_type_4', 'hh_type_5', 'hh_type_6']

final_table = final_table.merge(tabela9890_2, on='CD_FCU', how='left')

### Sanitation

In [17]:
# Type of Sanitation System 
tabela9892_2_type = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/Características dos Domicílios e dos Moradores/9892/tabela9892_2_tipo_esg_sanitario.xlsx', skiprows=5, skipfooter=1)
tabela9892_2_type = tabela9892_2_type[['Unnamed: 0', 'Rede geral ou pluvial', 'Fossa séptica ou fossa filtro ligada à rede', 'Fossa séptica ou fossa filtro não ligada à rede', 'Fossa rudimentar ou buraco', 'Vala', 'Rio, lago, córrego ou mar', 'Outra forma', 'Não tinham banheiro nem sanitário']]
tabela9892_2_type.columns = ['CD_FCU', 'sanit_1', 'sanit_2','sanit_3','sanit_4','sanit_5','sanit_6','sanit_7','no_bath']

final_table = final_table.merge(tabela9892_2_type, on='CD_FCU', how='left')

### Structure quality & attributes

In [18]:
# Existence of a Bathroom or Toilet and Number of Bathrooms for Exclusive Use of the Household
tabela9892_2 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/Características dos Domicílios e dos Moradores/9892/tabela9892_2_banheiros.xlsx', skiprows=5, skipfooter=1)
tabela9892_2 = tabela9892_2[['Unnamed: 0', 'Total.1', 'Total.6', 'Total.7', 'Total.8']]
tabela9892_2.columns = ['CD_FCU', 'excl_bath', 'shrd_bath','toilet','no_toilet']

final_table = final_table.merge(tabela9892_2, on='CD_FCU', how='left')

### Water

In [19]:
# Existence of Water Piping
tabela9891_2_pipe = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/Características dos Domicílios e dos Moradores/9891/tabela9891_2_canali_agua.xlsx', skiprows=5, skipfooter=1)
tabela9891_2_pipe = tabela9891_2_pipe[['Unnamed: 0', 'Total.1', 'Total.2', 'Total.3']]
tabela9891_2_pipe.columns = ['CD_FCU', 'wtr_pipe','wtr_semi','no_wtr_pipe']
# tabela9891_2_pipe['no_water_piping'] = tabela9891_2_pipe['no_water_piping'].replace('-', 0)
# tabela9891_2_pipe['water_semi_piping'] = tabela9891_2_pipe['water_semi_piping'].replace('-', 0)
# tabela9891_2_pipe['water_piping'] = tabela9891_2_pipe['water_piping'].replace('-', 0)
final_table = final_table.merge(tabela9891_2_pipe, on='CD_FCU', how='left')

# Main Water Supply Source
tabela9891_2_source = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/Características dos Domicílios e dos Moradores/9891/tabela9891_2_abast_agua.xlsx', skiprows=5, skipfooter=1)
tabela9891_2_source = tabela9891_2_source[['Unnamed: 0', 'Rede geral de distribuição', 'Poço profundo ou artesiano', 'Poço raso, freático ou cacimba', 'Fonte, nascente ou mina', 'Carro-pipa', 'Água da chuva armazenada', 'Rios, açudes, córregos, lagos e igarapés', 'Outra']]
tabela9891_2_source.columns = ['CD_FCU', 'wtr_dist','wtr_deep','wtr_shal','wtr_spring','wtr_truck','wtr_rain','wtr_river','wtr_oth']
final_table = final_table.merge(tabela9891_2_source, on='CD_FCU', how='left')

In [20]:
final_table

,CD_FCU,hh_density,age_index,median_age,sex_ratio,literate,race_wht,race_blk,race_ylw,race_brn,race_ind,race_unk,depriv_idx,priv_hh,coll_hh,hh_type_1,hh_type_2,hh_type_3,hh_type_4,hh_type_5,hh_type_6,sanit_1,sanit_2,sanit_3,sanit_4,sanit_5,sanit_6,sanit_7,no_bath,excl_bath,shrd_bath,toilet,no_toilet,wtr_pipe,wtr_semi,no_wtr_pipe,wtr_dist,wtr_deep,wtr_shal,wtr_spring,wtr_truck,wtr_rain,wtr_river,wtr_oth
0,11000490002,2.217391304347826,33.329999999999998,28,76,100.000000000000000,33.329999999999998,9.800000000000001,-,52.939999999999998,3.920000000000000,-,-1.190800020270165,100.000000000000000,-,91.299999999999997,8.699999999999999,-,-,-,-,47.829999999999998,-,30.430000000000000,21.739999999999998,-,-,-,-,100,-,-,-,100,-,-,100,-,-,-,-,-,-,-
1,11000490006,2.795454545454545,32.030000000000001,29,111,90.109999999999999,26.829999999999998,14.840000000000000,0.810000000000000,57.320000000000000,0.200000000000000,-,1.348939830389360,100.000000000000000,-,100,-,-,-,-,-,1.140000000000000,-,10.800000000000001,88.069999999999993,-,-,-,-,100,-,-,-,100,-,-,88.069999999999993,2.840000000000000,9.090000000000000,-,-,-,-,-
2,11001060003,3.750000000000000,14.680000000000000,23,94,94.420000000000002,7.780000000000000,10,0.480000000000000,78.250000000000000,3.490000000000000,-,0.704954464215429,100.000000000000000,-,100,-,-,-,-,-,-,-,1.790000000000000,92.260000000000005,-,-,4.170000000000000,1.790000000000000,95.239999999999995,0.600000000000000,2.380000000000000,1.790000000000000,92.859999999999999,1.190000000000000,5.950000000000000,27.980000000000000,21.430000000000000,47.619999999999997,-,-,-,-,2.980000000000000
3,11001060004,3.455128205128205,21.510000000000002,25,115,91.549999999999997,12.619999999999999,16.510000000000002,-,65.310000000000002,5.570000000000000,-,2.122344372690510,100.000000000000000,-,94.870000000000005,-,3.210000000000000,1.920000000000000,-,-,-,1.280000000000000,83.329999999999998,11.539999999999999,3.210000000000000,-,-,0.640000000000000,85.260000000000005,5.130000000000000,8.970000000000001,0.640000000000000,82.049999999999997,16.030000000000001,1.920000000000000,21.149999999999999,55.130000000000003,23.719999999999999,-,-,-,-,-
4,11001060005,3.419354838709677,27.489999999999998,24,108,89.280000000000001,17.640000000000001,11.699999999999999,0.190000000000000,68.870000000000005,1.600000000000000,-,3.261340538797059,100.000000000000000,-,99.030000000000001,0.320000000000000,0.650000000000000,-,-,-,-,-,-,69.030000000000001,29.030000000000001,-,0.320000000000000,1.610000000000000,67.099999999999994,3.870000000000000,27.420000000000002,1.610000000000000,57.100000000000001,22.260000000000002,20.649999999999999,-,8.060000000000000,81.939999999999998,3.230000000000000,-,-,-,6.770000000000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,53001080089,3.186536901865369,22.710000000000001,30,101,96.879999999999995,30.410000000000000,12.710000000000001,0.300000000000000,56.409999999999997,0.180000000000000,-,1.277365421646900,100.000000000000000,-,95.640000000000001,4.230000000000000,0.080000000000000,0.030000000000000,-,0.030000000000000,4.070000000000000,0.620000000000000,44.939999999999998,50.229999999999997,0.080000000000000,-,0.050000000000000,-,99.969999999999999,-,0.030000000000000,-,98.370000000000005,1.110000000000000,0.520000000000000,4.200000000000000,79.430000000000007,15.800000000000001,0.140000000000000,0.080000000000000,0.190000000000000,-,0.160000000000000
12344,53001080090,2.815789473684211,14.020000000000000,26,96,89.250000000000000,17.449999999999999,11.529999999999999,-,71.030000000000001,-,-,2.599055443227950,100.000000000000000,-,100,-,-,-,-,-,2.900000000000000,-,1.450000000000000,88.409999999999997,5.800000000000000,-,1.450000000000000,-,89.859999999999999,2.900000000000000,7.250000000000000,-,91.299999999999997,5.800000000000000,2.900000000000000,95.650000000000006,1.450000000000000,-,-,-,-,-,2.900000000000000
12345,53001080094,2.991935483870968,18.520000000000000,25,111,93.159999999999997,24.530000000000001,23.719999999999999,0.270000000000000,51.210000000000001,0.270000000000000,-,-0.129648558890625,100.000000000000000,-,100,-,-,-,-,-,0.930000000000000,0.930000000000000,34.259999999999998,62.960000000000001,-,-,-,0.930000000000000,98.150000000000006,0.930000000000000,-,0.930000000000000,92.590000000000003,-,7.410000000000000,2.780000000000000,18.520000000000000,77.780000000000001,-,-,-,-,0.930000000000000
12346,53001080095,2.926470588235294,25.100000000000001,27,105,93.870000000000005,25.469999999999999,8.890000000000001,0.100000000000000,65.530000000000001,-,-,1.065393206436609,100.000000000000000,-,94.719999999999999,-,0.290000000000000,4.990000000000000,-,-,0.290000000000000,0.590000000000000,8.800000000000001,89.739999999999995,0.590000000000000,-,-,-,100,-,-,-,99.409999999999997,0.590000000000000,-,98.829999999999998,0.590000000000000,-,0.290000000000000,-,-,-,0.290000000000000
12347,53001080096,3.133928571428572,47.439999999999998,32,96,97.439999999999998,33.329999999999998,10.830000000000000,-,55.840000000000003,-,-,-1.739138832075000,100.000000000000000,-,100,-,-,-,-,-,2.680000000000000,-,65.180000000000007,32.140000000000001,-,-,-,-,99.109999999999999,0.890000000000000,-,-,100,-,-,94.640000000000001,5.360000000000000,-,-,-,-,-,-

# WITHIN AREA LEVEL

## Physical Hazards & Asset

### Ecological diversity

In [21]:
mapbiomas2023 = gpd.read_file('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/poligonos/Mapbiomas/mapbiomas_2023.shp')
mapbiomas2023 = mapbiomas2023[mapbiomas2023['area_favel'] > 0]
mapbiomas2023

# Vegetation area
# Water area
# porcentagem da area
mapbiomas2023['wtr_area'] = (mapbiomas2023['agua'] / mapbiomas2023['area_favel']) * 100
mapbiomas2023['veg_area'] = ((mapbiomas2023['veg_intra_'] + mapbiomas2023['frag_veg']) / mapbiomas2023['area_favel']) * 100

ecological = mapbiomas2023[['cd_fcu', 'wtr_area', 'veg_area']]
ecological.columns = ['CD_FCU', 'wtr_area', 'veg_area']

final_table = final_table.merge(ecological, on='CD_FCU', how='left')

### Natural hazards (slope, flood zone)

In [22]:
# Risk area
# Declive area
# HAND
mapbiomas2023['risk'] = (mapbiomas2023['risco'] / mapbiomas2023['area_favel']) * 100
mapbiomas2023['slope_10'] = (mapbiomas2023['decliv_10'] / mapbiomas2023['area_favel']) * 100
mapbiomas2023['slope_20'] = (mapbiomas2023['decliv_20'] / mapbiomas2023['area_favel']) * 100
mapbiomas2023['slope_30'] = (mapbiomas2023['decliv_30'] / mapbiomas2023['area_favel']) * 100
mapbiomas2023['slope_30p'] = (mapbiomas2023['decliv_mai'] / mapbiomas2023['area_favel']) * 100
mapbiomas2023['hand_6p'] = (mapbiomas2023['hand_acima'] / mapbiomas2023['area_favel']) * 100
mapbiomas2023['hand_0_3'] = (mapbiomas2023['hand_ate_3'] / mapbiomas2023['area_favel']) * 100
mapbiomas2023['hand_3_6'] = (mapbiomas2023['hand_ate_6'] / mapbiomas2023['area_favel']) * 100


natural_hazards = mapbiomas2023[['cd_fcu', 'risk', 'slope_10', 'slope_20', 'slope_30', 'slope_30p', 'hand_6p', 'hand_3_6', 'hand_0_3']]
natural_hazards.columns = ['CD_FCU', 'risk_area', 'slope_10', 'slope_20', 'slope_30', 'slope_30p', 'hand_6p', 'hand_3_6', 'hand_0_3']

final_table = final_table.merge(natural_hazards, on='CD_FCU', how='left')
final_table

,CD_FCU,hh_density,age_index,median_age,sex_ratio,literate,race_wht,race_blk,race_ylw,race_brn,race_ind,race_unk,depriv_idx,priv_hh,coll_hh,hh_type_1,hh_type_2,hh_type_3,hh_type_4,hh_type_5,hh_type_6,sanit_1,sanit_2,sanit_3,sanit_4,sanit_5,sanit_6,sanit_7,no_bath,excl_bath,shrd_bath,toilet,no_toilet,wtr_pipe,wtr_semi,no_wtr_pipe,wtr_dist,wtr_deep,wtr_shal,wtr_spring,wtr_truck,wtr_rain,wtr_river,wtr_oth,wtr_area,veg_area,risk_area,slope_10,slope_20,slope_30,slope_30p,hand_6p,hand_3_6,hand_0_3
0,11000490002,2.217391304347826,33.329999999999998,28,76,100.000000000000000,33.329999999999998,9.800000000000001,-,52.939999999999998,3.920000000000000,-,-1.190800020270165,100.000000000000000,-,91.299999999999997,8.699999999999999,-,-,-,-,47.829999999999998,-,30.430000000000000,21.739999999999998,-,-,-,-,100,-,-,-,100,-,-,100,-,-,-,-,-,-,-,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,58.888895797795861,41.111104202204125,0.000000000000000
1,11000490006,2.795454545454545,32.030000000000001,29,111,90.109999999999999,26.829999999999998,14.840000000000000,0.810000000000000,57.320000000000000,0.200000000000000,-,1.348939830389360,100.000000000000000,-,100,-,-,-,-,-,1.140000000000000,-,10.800000000000001,88.069999999999993,-,-,-,-,100,-,-,-,100,-,-,88.069999999999993,2.840000000000000,9.090000000000000,-,-,-,-,-,0.000000000000000,20.996133162592013,0.000000000000000,77.174972009008101,22.825027990991934,0.000000000000000,0.000000000000000,42.196649969163154,38.263101147739988,19.540248883096929
2,11001060003,3.750000000000000,14.680000000000000,23,94,94.420000000000002,7.780000000000000,10,0.480000000000000,78.250000000000000,3.490000000000000,-,0.704954464215429,100.000000000000000,-,100,-,-,-,-,-,-,-,1.790000000000000,92.260000000000005,-,-,4.170000000000000,1.790000000000000,95.239999999999995,0.600000000000000,2.380000000000000,1.790000000000000,92.859999999999999,1.190000000000000,5.950000000000000,27.980000000000000,21.430000000000000,47.619999999999997,-,-,-,-,2.980000000000000,0.000000000000000,14.763930042967885,0.000000000000000,99.097335612453449,0.902664387546549,0.000000000000000,0.000000000000000,7.770582001272489,28.163167108480323,64.066250890247204
3,11001060004,3.455128205128205,21.510000000000002,25,115,91.549999999999997,12.619999999999999,16.510000000000002,-,65.310000000000002,5.570000000000000,-,2.122344372690510,100.000000000000000,-,94.870000000000005,-,3.210000000000000,1.920000000000000,-,-,-,1.280000000000000,83.329999999999998,11.539999999999999,3.210000000000000,-,-,0.640000000000000,85.260000000000005,5.130000000000000,8.970000000000001,0.640000000000000,82.049999999999997,16.030000000000001,1.920000000000000,21.149999999999999,55.130000000000003,23.719999999999999,-,-,-,-,-,0.000000000000000,32.384311516935455,0.000000000000000,98.721663434389768,1.278336565610250,0.000000000000000,0.000000000000000,41.867153867390421,30.051487191010601,28.081358941598968
4,11001060005,3.419354838709677,27.489999999999998,24,108,89.280000000000001,17.640000000000001,11.699999999999999,0.190000000000000,68.870000000000005,1.600000000000000,-,3.261340538797059,100.000000000000000,-,99.030000000000001,0.320000000000000,0.650000000000000,-,-,-,-,-,-,69.030000000000001,29.030000000000001,-,0.320000000000000,1.610000000000000,67.099999999999994,3.870000000000000,27.420000000000002,1.610000000000000,57.100000000000001,22.260000000000002,20.649999999999999,-,8.060000000000000,81.939999999999998,3.230000000000000,-,-,-,6.770000000000000,0.000000000000000,16.810270033450074,0.000000000000000,97.029398273549816,2.970601726450190,0.000000000000000,0.000000000000000,16.551773293886008,29.041596935975221,54.406629770138771
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,53001080089,3.186536901865369,22.710000000000001,30,101,96.879999999999995,30.410000000000000,12.710000000000001,0.300000000000000,56.409999999999997,0.180000000000000,-,1.277365421646900,100.000000000000000,-,95.640000000000001,4.230000000000000,0.080000000000000,0.030000000000000,-,0.030000000000000,4.070000000000000,0.620000000000000,44.939999999999998,50.229999999999997,0.080000000000000,-,0.050000000000000,-,99.969999999999999,-,0.030000000000000,-,98.370000000000005,1.110000000000000,0.520000000000000,4.200000000000000,79.430000000000007,15.800000000000001,0.140000000000000,0.080000000000000,0.190000000000000,-,0.160000000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12344,53001080090,2.815789473684211,14.020000000000000,26,96,89.250000000000000,17.449999999999999,11.529999999999999,-,71.030000000000001,-,-,2.599055443227950,100.000000000000000,-,100,-,-,-,-,-,2.900000000000000,-,1.450000000000000,88.409999999999997,5.800000000000000,-,1.450000000000000,-,89.859999999999999,2.900000000000000,7.250000000000000,-,91.299999999999997,5.800000000000000,2.900000000000000,95.650000000000006,1.450000000000000,-,-,-,-,-,2.900000000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12345,53001080094,2.991935483870968,18.520000000000000,25,111,93.159999999999997,24.530000000000001,23.719999999999999,0.270000000000000,51.210000000000001,0.270000000000000,-,-0.129648558890625,100.000000000000000,-,100,-,-,-,-,-,0.930000000000000,0.930000000000000,34.259999999999998,62.960000000000001,-,-,-,0.930000000000000,98.150000000000006,0.930000000000000,-,0.930000000000000,92.590000000000003,-,7.410000000000000,2.780000000000000,18.520000000000000,77.780000000000001,-,-,-,-,0.930000000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12346,53001080095,2.926470588235294,25.100000000000001,27,105,93.870000000000005,25.469999999999999,8.890000000000001,0.100000000000000,65.530000000000001,-,-,1.065393206436609,100.000000000000000,-,94.719999999999999,-,0.290000000000000,4.990000000000000,-,-,0.290000000000000,0.590000000000000,8.800000000000001,89.739999999999995,0.590000000000000,-,-,-,100,-,-,-,99.409999999999997,0.590000000000000,-,98.829999999999998,0.590000000000000,-,0.290000000000000,-,-,-,0.290000000000000,0.000000000000000,6.416914225024783,0.000000000000000,39.753132139665411,50.208664333526642,10.038203526807948,0.000000000000000,62.198742347815980,16.005125473218570,21.796132178965447
12347,53001080096,3.133928571428572,47.439999999999998,32,96,97.439999999999998,33.329999999999998,10.830000000000000,-,55.840000000000003,-,-,-1.739138832075000,100.000000000000000,-,100,-,-,-,-,-,2.680000000000000,-,65.180000000000007,32.140000000000001,-,-,-,-,99.109999999999999,0.890000000000000,-,-,100,-,-,94.640000000000001,5.360000000000000,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Contamination

### Air pollution

In [23]:
# Sulphur Dioxide (SO₂)
# Nitrogen Dioxide (NO₂)
# Ozone (O₃)
# Carbon Monoxide (CO)
sentinel5P = gpd.read_file('../../dataset/air_pollution/air_pollution.shp')
sentinel5P = sentinel5P[['cd_fcu', 'SO2_mean', 'CO_mean', 'O3_mean', 'NO2_mean']]
sentinel5P.columns = ['CD_FCU', 'SO2', 'CO', 'O3', 'NO2']
sentinel5P['CD_FCU'] = sentinel5P['CD_FCU'].astype(int)

# sentinel5P
final_table = final_table.merge(sentinel5P, on='CD_FCU', how='left')

### Garbage accumulation

In [24]:
# Waste Disposal Method by household
tabela9893_2 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/Características dos Domicílios e dos Moradores/9893/tabela9893_2_dest_lixo.xlsx', skiprows=4, skipfooter=1)
tabela9893_2 = tabela9893_2[['Unnamed: 0', 'Coletado']]
tabela9893_2.columns = ['CD_FCU', 'waste_coll']
# replace "-" by 0 waste_collected column
# tabela9893_2['waste_collected'] = tabela9893_2['waste_collected'].replace('-', 0)
final_table = final_table.merge(tabela9893_2, on='CD_FCU', how='left')

## Unplanned Urbanization

### Building or population density

In [25]:
# Demographic density in slums and urban communities (Inhabitants per square kilometer)
tabela9888_3 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/Estabelecimentos e Território/9888/tabela9888_3.xlsx', skiprows=3, skipfooter=1)
tabela9888_3 = tabela9888_3[['Unnamed: 0', '2022']]
tabela9888_3.columns = ['CD_FCU', 'demo_dens']
final_table = final_table.merge(tabela9888_3, on='CD_FCU', how='left')

# Density of establishments
tabela9888_2 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/Estabelecimentos e Território/9888/tabela9888_2.xlsx', skiprows=3, skipfooter=1)
tabela9889_1 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/Estabelecimentos e Território/9889/tabela9889_1.xlsx', skiprows=4, skipfooter=1)
tabela9888_2 = tabela9888_2[['Unnamed: 0', '2022']]
tabela9888_2.columns = ['CD_FCU', 'area']
tabela9889_1 = tabela9889_1[['Unnamed: 0', 'Total']]
tabela9889_1.columns = ['CD_FCU', 'total']
density_of_establishments = tabela9888_2.merge(tabela9889_1, on='CD_FCU', how='left')
density_of_establishments['est_dens'] = density_of_establishments['total'] / density_of_establishments['area']
density_of_establishments.drop(columns=['area', 'total'], inplace=True)
final_table = final_table.merge(density_of_establishments, on='CD_FCU', how='left')

### Building uses or functions

In [26]:
# Establishments by type
tabela9889_3 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/Estabelecimentos e Território/9889/tabela9889_3.xlsx', skiprows=4, skipfooter=1)
tabela9889_3 = tabela9889_3[['Unnamed: 0', 'Estabelecimento de ensino', 'Estabelecimento de saúde', 'Estabelecimento religioso', 'Estabelecimento agropecuário', 'Estabelecimentos de outras finalidades', 'Edificação em construção ou em reforma']]
tabela9889_3.columns = ['CD_FCU', 'est_edu','est_health','est_relig','est_agri','est_other','est_const']

final_table = final_table.merge(tabela9889_3, on='CD_FCU', how='left')

### Coverage or area of green space

In [27]:
# Intra-urban vegetation
mapbiomas2023['intra_veg'] = mapbiomas2023['veg_intra_']
veg = mapbiomas2023[['cd_fcu', 'intra_veg']]
veg.columns = ['CD_FCU', 'intra_veg']

final_table = final_table.merge(veg, on='CD_FCU', how='left')

# AREA CONNECT LEVEL

## Facilities & Services

### Availability/distance -health

In [28]:
# # from shapely.geometry import Point

# # Primary Care Hospitals
# favelas = gpd.read_file("/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/poligonos/fcu_blank/qg_2022_670_fcu_agreg.shp")
# primary_care_hospitals = gpd.read_file("/Volumes/ssd/Doutorado/DATASET/IBGE/base_grafica AGSN 2019/ESaude_Atencao_Primaria/ESaude_Atencao_Primaria.shp")
# inpatient_hospitals = gpd.read_file("/Volumes/ssd/Doutorado/DATASET/IBGE/base_grafica AGSN 2019/ESaude_Internacao_Observacao/ESaude_Internacao_Observacao.shp")

# # Garantir que ambos estão no mesmo sistema de coordenadas
# favelas = favelas.to_crs(epsg=3857)  # Exemplo: métrico (metros)
# primary_care_hospitals = primary_care_hospitals.to_crs(favelas.crs)
# inpatient_hospitals = inpatient_hospitals.to_crs(favelas.crs)

# # Criar lista de geometrias dos hospitais
# primary_care_hospital_points = primary_care_hospitals.geometry.tolist()
# inpatient_hospital_points = inpatient_hospitals.geometry.tolist()

# count = 0

# # Função para calcular distância
# def distancia_mais_proxima(polygon):
#     global count
#     count += 1
#     print(count)
#     distances = {}
#     centroide = polygon.centroid

#     if any(polygon.contains(p) for p in primary_care_hospital_points):
#         distances['primary_care_hospital'] = 0
#     else:
#         distances['primary_care_hospital'] = min(centroide.distance(p) for p in primary_care_hospital_points)
    
#     if any(polygon.contains(p) for p in inpatient_hospital_points):
#         distances['inpatient_hospital'] = 0
#     else:
#         distances['inpatient_hospital'] = min(centroide.distance(p) for p in inpatient_hospital_points)
    
#     return distances

# favelas['dist_primary_care_hospital', 'dist_inpatient_hospital'] = favelas.geometry.apply(distancia_mais_proxima)
# favelas['primary_care_hospital'] = favelas['hospital_distance'].apply(lambda x: x['primary_care_hospital'])
# favelas['inpatient_hospital'] = favelas['hospital_distance'].apply(lambda x: x['inpatient_hospital'])
# favelas = favelas[['cd_fcu', 'primary_care_hospital', 'inpatient_hospital']]
# favelas.columns = ['CD_FCU', 'primary_care_hospital', 'inpatient_hospital']
# favelas['CD_FCU'] = favelas['CD_FCU'].astype(int)
# final_table = final_table.merge(favelas, on='CD_FCU', how='left')

In [29]:

dist_hospitals = gpd.read_file('/Volumes/ssd/Doutorado/DATASET/IBGE/base_grafica AGSN 2019/DIST_HOSPITALS/dist_hospitals_2019.shp')
dist_hospitals = dist_hospitals[['cd_fcu', 'primary_ca', 'inpatient_']]
dist_hospitals.columns = ['CD_FCU', 'prim_hosp', 'inp_hosp']
dist_hospitals['CD_FCU'] = dist_hospitals['CD_FCU'].astype(int)


final_table = final_table.merge(dist_hospitals, on='CD_FCU', how='left')
final_table

,CD_FCU,hh_density,age_index,median_age,sex_ratio,literate,race_wht,race_blk,race_ylw,race_brn,race_ind,race_unk,depriv_idx,priv_hh,coll_hh,hh_type_1,hh_type_2,hh_type_3,hh_type_4,hh_type_5,hh_type_6,sanit_1,sanit_2,sanit_3,sanit_4,sanit_5,sanit_6,sanit_7,no_bath,excl_bath,shrd_bath,toilet,no_toilet,wtr_pipe,wtr_semi,no_wtr_pipe,wtr_dist,wtr_deep,wtr_shal,wtr_spring,wtr_truck,wtr_rain,wtr_river,wtr_oth,wtr_area,veg_area,risk_area,slope_10,slope_20,slope_30,slope_30p,hand_6p,hand_3_6,hand_0_3,SO2,CO,O3,NO2,waste_coll,demo_dens,est_dens,est_edu,est_health,est_relig,est_agri,est_other,est_const,intra_veg,prim_hosp,inp_hosp
0,11000490002,2.217391304347826,33.329999999999998,28,76,100.000000000000000,33.329999999999998,9.800000000000001,-,52.939999999999998,3.920000000000000,-,-1.190800020270165,100.000000000000000,-,91.299999999999997,8.699999999999999,-,-,-,-,47.829999999999998,-,30.430000000000000,21.739999999999998,-,-,-,-,100,-,-,-,100,-,-,100,-,-,-,-,-,-,-,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,58.888895797795861,41.111104202204125,0.000000000000000,-0.000029989798561,0.048340430846152,0.115784465294689,0.000049376462248,100,1388.809999999999945,162.162162162162161,-,-,-,-,100,-,0.000000000000000,278.590762211160381,1200.794831089852323
1,11000490006,2.795454545454545,32.030000000000001,29,111,90.109999999999999,26.829999999999998,14.840000000000000,0.810000000000000,57.320000000000000,0.200000000000000,-,1.348939830389360,100.000000000000000,-,100,-,-,-,-,-,1.140000000000000,-,10.800000000000001,88.069999999999993,-,-,-,-,100,-,-,-,100,-,-,88.069999999999993,2.840000000000000,9.090000000000000,-,-,-,-,-,0.000000000000000,20.996133162592013,0.000000000000000,77.174972009008101,22.825027990991934,0.000000000000000,0.000000000000000,42.196649969163154,38.263101147739988,19.540248883096929,-0.000004476528898,0.048091396019009,0.115805332255976,0.000049817524189,99.430000000000007,3400.159999999999854,179.310344827586221,-,-,100,-,100,100,14131.215856215536405,1196.761653431363357,2511.709247268609033
2,11001060003,3.750000000000000,14.680000000000000,23,94,94.420000000000002,7.780000000000000,10,0.480000000000000,78.250000000000000,3.490000000000000,-,0.704954464215429,100.000000000000000,-,100,-,-,-,-,-,-,-,1.790000000000000,92.260000000000005,-,-,4.170000000000000,1.790000000000000,95.239999999999995,0.600000000000000,2.380000000000000,1.790000000000000,92.859999999999999,1.190000000000000,5.950000000000000,27.980000000000000,21.430000000000000,47.619999999999997,-,-,-,-,2.980000000000000,0.000000000000000,14.763930042967885,0.000000000000000,99.097335612453449,0.902664387546549,0.000000000000000,0.000000000000000,7.770582001272489,28.163167108480323,64.066250890247204,-0.000060184380603,0.050244105414220,0.115536725440938,0.000047722047153,96.430000000000007,2338.940000000000055,78.066914498141259,-,-,-,-,100,100,33248.404849781712983,1314.395892399512377,2430.208661920258692
3,11001060004,3.455128205128205,21.510000000000002,25,115,91.549999999999997,12.619999999999999,16.510000000000002,-,65.310000000000002,5.570000000000000,-,2.122344372690510,100.000000000000000,-,94.870000000000005,-,3.210000000000000,1.920000000000000,-,-,-,1.280000000000000,83.329999999999998,11.539999999999999,3.210000000000000,-,-,0.640000000000000,85.260000000000005,5.130000000000000,8.970000000000001,0.640000000000000,82.049999999999997,16.030000000000001,1.920000000000000,21.149999999999999,55.130000000000003,23.719999999999999,-,-,-,-,-,0.000000000000000,32.384311516935455,0.000000000000000,98.721663434389768,1.278336565610250,0.000000000000000,0.000000000000000,41.867153867390421,30.051487191010601,28.081358941598968,-0.000050918034876,0.050180077218405,0.115517229197630,0.000047522635007,96.150000000000006,1835.130000000000109,64.625850340136054,-,100,-,-,100,100,66774.124700329353800,1295.298272811971174,3364.276391422291908
4,11001060005,3.419354838709677,27.489999999999998,24,108,89.280000000000001,17.640000000000001,11.699999999999999,0.190000000000000,68.870000000000005,1.600000000000000,-,3.261340538797059,100.000000000000000,-,99.030000000000001,0.320000000000000,0.650000000000000,-,-,-,-,-,-,69.030000000000001,29.030000000000001,-,0.320000000000000,1.610000000000000,67.099999999999994,3.870000000000000,27.420000000000002,1.610000000000000,57.100000000000001,22.260000000000002,20.649999999999999,-,8.060000000000000,81.939999999999998,3.230000000000000,-,-,-,6.770000000000000,0.000000000000000,16.810270033450074,0.000000000000000,97.029398273549816,2.970601726450190,0.000000000000000,0.000000000000000,16.551773293886008,29.041596935975221,54.406629770138771,-0.000048996831748,0.050498392910555,0.115498048523921,0.000046854430072,91.939999999999998,1751.039999999999964,66.115702479338850,-,-,100,-,100,100,51840.937377929687500,1100.884940293557975,5707.936643438444662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,53001080089,3.186536901865369,22.710000000000001,30,101,96.879999999999995,30.410000000000000,12.710000000000001,0.300000000000000,56.409999999999997,0.180000000000000,-,1.277365421646900,100.000000000000000,-,95.640000000000001,4.230000000000000,0.080000000000000,0.030000000000000,-,0.030000000000000,4.070000000000000,0.620000000000000,44.939999999999998,50.229999999999997,0.080000000000000,-,0.050000000000000,-,99.969999999999999,-,0.030000000000000,-,98.370000000000005,1.110000000000000,0.520000000000000,4.200000000000000,79.430000000000007,15.800000000000001,0.140000000000000,0.080000000000000,0.190000000000000,-,0.160000000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000037125215130,0.029717233120341,0.114947991722667,0.000060037085301,95.090000000000003,1123.279999999999973,111.312303440388831,-,100,100,100,100,100,NaN,3149.617735287526102,7569.054889072691367
12344,53001080090,2.815789473684211,14.020000000000000,26,96,89.250000000000000,17.449999999999999,11.529999999999999,-,71.030000000000001,-,-,2.599055443227950,100.000000000000000,-,100,-,-,-,-,-,2.900000000000000,-,1.450000000000000,88.409999999999997,5.800000000000000,-,1.450000000000000,-,89.859999999999999,2.900000000000000,7.250000000000000,-,91.299999999999997,5.800000000000000,2.900000000000000,95.650000000000006,1.450000000000000,-,-,-,-,-,2.900000000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000064994182514,0.030199098735347,0.115141811282508,0.000051950798235,78.260000000000005,1483.119999999999891,171.296296296296305,-,-,-,-,100,100,NaN,1988.238292009416682,2671.917043771586577
12345,53001080094,2.991935483870968,18.520000000000000,25,111,93.159999999999997,24.530000000000001,23.719999999999999,0.270000000000000,51.210000000000001,0.270000000000000,-,-0.129648558890625,100.000000000000000,-,100,-,-,-,-,-,0.930000000000000,0.930000000000000,34.259999999999998,62.960000000000001,-,-,-,0.930000000000000,98.150000000000006,0.930000000000000,-,0.930000000000000,92.590000000000003,-,7.410000000000000,2.780000000000000,18.520000000000000,77.780000000000001,-,-,-,-,0.930000000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000065102582200,0.029591776551053,0.115005619492870,0.000060315440674,95.370000000000005,2242.559999999999945,230.303030303030283,-,-,100,-,100,100,NaN,2356.262461572796383,1886.939243531011243
12346,53001080095,2.926470588235294,25.100000000000001,27,105,93.870000000000005,25.469999999999999,8.890000000000001,0.100000000000000,65.530000000000001,-,-,1.065393206436609,100.000000000000000,-,94.719999999999999,-,0.290000000000000,4.990000000000000,-,-,0.290000000000000,0.590000000000000,8.800000000000001,89.739999999999995,0.590000000000000,-,-,-,100,-,-,-,99.409999999999997,0.590000000000000,-,98.829999999999998,0.590000000000000,-,0.290000000000000,-,-,-,0.290000000000000,0.000000000000000,6.416914225024783,0.000000000000000,39.753132139665411,50.208664333526642,10.038203526807948,0.000000000000000,62.198742347815980,16.005125473218570,21.796132178965447,0.000008453422918,0.030349339927874,0.115278498127415,0.000059539555808,99.709999999999994,1687.150000000000091,57.335581787521079,-,-,100,-,100,100,17255.451816932829388,1408.288020310634238,8057.811878181278189
12347,53001080096,3.133928571428572,47.439999999999998,32,96,97.439999999999998,33.329999999999998,10.830000000000000,-,55.840000000000003,-,-,-1.739138832075000,100.000000000000000,-,100,-,-,-,-,-,2.680000000000000,-,65.180000000000007,32.140000000000001,-,-,-,-,99.109999999999999,0.890000000000000,-,-,100,-,-,94.640000000000001,5.360000000000000,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000005768214069,0.029483562236572,0.115130013672384,0.000058122273245,100,4710.899999999999636,253.333333333333343,100,-,100,-,100,100,NaN,5860.596567147706992,522.414700045862219

# FINAL JOIN

In [30]:
polygons = gpd.read_file("/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/poligonos/fcu_blank/qg_2022_670_fcu_agreg.shp")
polygons = polygons[['cd_fcu', 'geometry']]
polygons.columns = ['CD_FCU', 'geometry']
polygons['CD_FCU'] = polygons['CD_FCU'].astype(int)

final_table = final_table.merge(polygons, on='CD_FCU', how='left')

In [31]:
# replace - by 0 in all columns
final_table = final_table.replace('-', 0)
final_table

/var/folders/5l/x3ysgz0n0mvd7msxlmn75zhw0000gp/T/ipykernel_75630/3385324347.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_table = final_table.replace('-', 0)

,CD_FCU,hh_density,age_index,median_age,sex_ratio,literate,race_wht,race_blk,race_ylw,race_brn,race_ind,race_unk,depriv_idx,priv_hh,coll_hh,hh_type_1,hh_type_2,hh_type_3,hh_type_4,hh_type_5,hh_type_6,sanit_1,sanit_2,sanit_3,sanit_4,sanit_5,sanit_6,sanit_7,no_bath,excl_bath,shrd_bath,toilet,no_toilet,wtr_pipe,wtr_semi,no_wtr_pipe,wtr_dist,wtr_deep,wtr_shal,wtr_spring,wtr_truck,wtr_rain,wtr_river,wtr_oth,wtr_area,veg_area,risk_area,slope_10,slope_20,slope_30,slope_30p,hand_6p,hand_3_6,hand_0_3,SO2,CO,O3,NO2,waste_coll,demo_dens,est_dens,est_edu,est_health,est_relig,est_agri,est_other,est_const,intra_veg,prim_hosp,inp_hosp,geometry
0,11000490002,2.217391304347826,33.329999999999998,28,76,100.000000000000000,33.329999999999998,9.800000000000001,0.000000000000000,52.939999999999998,3.920000000000000,0.000000000000000,-1.190800020270165,100.000000000000000,0.000000000000000,91.299999999999997,8.699999999999999,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,47.829999999999998,0.000000000000000,30.430000000000000,21.739999999999998,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,58.888895797795861,41.111104202204125,0.000000000000000,-0.000029989798561,0.048340430846152,0.115784465294689,0.000049376462248,100.000000000000000,1388.809999999999945,162.162162162162161,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,278.590762211160381,1200.794831089852323,"POLYGON ((-61.44456 -11.42432, -61.44547 -11.4..."
1,11000490006,2.795454545454545,32.030000000000001,29,111,90.109999999999999,26.829999999999998,14.840000000000000,0.810000000000000,57.320000000000000,0.200000000000000,0.000000000000000,1.348939830389360,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.140000000000000,0.000000000000000,10.800000000000001,88.069999999999993,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,88.069999999999993,2.840000000000000,9.090000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,20.996133162592013,0.000000000000000,77.174972009008101,22.825027990991934,0.000000000000000,0.000000000000000,42.196649969163154,38.263101147739988,19.540248883096929,-0.000004476528898,0.048091396019009,0.115805332255976,0.000049817524189,99.430000000000007,3400.159999999999854,179.310344827586221,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,14131.215856215536405,1196.761653431363357,2511.709247268609033,"POLYGON ((-61.47698 -11.4123, -61.47698 -11.41..."
2,11001060003,3.750000000000000,14.680000000000000,23,94,94.420000000000002,7.780000000000000,10.000000000000000,0.480000000000000,78.250000000000000,3.490000000000000,0.000000000000000,0.704954464215429,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.790000000000000,92.260000000000005,0.000000000000000,0.000000000000000,4.170000000000000,1.790000000000000,95.239999999999995,0.600000000000000,2.380000000000000,1.790000000000000,92.859999999999999,1.190000000000000,5.950000000000000,27.980000000000000,21.430000000000000,47.619999999999997,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,2.980000000000000,0.000000000000000,14.763930042967885,0.000000000000000,99.097335612453449,0.902664387546549,0.000000000000000,0.000000000000000,7.770582001272489,28.163167108480323,64.066250890247204,-0.000060184380603,0.050244105414220,0.115536725440938,0.000047722047153,96.430000000000007,2338.940000000000055,78.066914498141259,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,33248.404849781712983,1314.395892399512377,2430.208661920258692,"POLYGON ((-65.3154 -10.79052, -65.31845 -10.79..."
3,11001060004,3.455128205128205,21.510000000000002,25,115,91.549999999999997,12.619999999999999,16.510000000000002,0.000000000000000,65.310000000000002,5.570000000000000,0.000000000000000,2.122344372690510,100.000000000000000,0.000000000000000,94.870000000000005,0.000000000000000,3.210000000000000,1.920000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.280000000000000,83.329999999999998,11.539999999999999,3.210000000000000,0.000000000000000,0.000000000000000,0.640000000000000,85.260000000000005,5.130000000000000,8.970000000000001,0.640000000000000,82.049999999999997,16.030000000000001,1.920000000000000,21.149999999999999,55.130000000000003,23.719999999999999,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,32.384311516935455,0.000000000000000,98.721663434389768,1.278336565610250,0.000000000000000,0.000000000000000,41.867153867390421,30.051487191010601,28.081358941598968,-0.000050918034876,0.050180077218405,0.115517229197630,0.000047522635007,96.150000000000006,1835.130000000000109,64.625850340136054,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,66774.124700329353800,1295.298272811971174,3364.276391422291908,"POLYGON ((-65.30695 -10.78101, -65.30776 -10.7..."
4,11001060005,3.419354838709677,27.489999999999998,24,108,89.280000000000001,17.640000000000001,11.699999999999999,0.190000000000000,68.870000000000005,1.600000000000000,0.000000000000000,3.261340538797059,100.000000000000000,0.000000000000000,99.030000000000001,0.320000000000000,0.650000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,69.030000000000001,29.030000000000001,0.000000000000000,0.320000000000000,1.610000000000000,67.099999999999994,3.870000000000000,27.420000000000002,1.610000000000000,57.100000000000001,22.260000000000002,20.649999999999999,0.000000000000000,8.060000000000000,81.939999999999998,3.230000000000000,0.000000000000000,0.000000000000000,0.000000000000000,6.770000000000000,0.000000000000000,16.810270033450074,0.000000000000000,97.029398273549816,2.970601726450190,0.000000000000000,0.000000000000000,16.551773293886008,29.041596935975221,54.406629770138771,-0.000048996831748,0.050498392910555,0.115498048523921,0.000046854430072,91.939999999999998,1751.039999999999964,66.115702479338850,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,51840.937377929687500,1100.884940293557975,5707.936643438444662,"POLYGON ((-65.29101 -10.76165, -65.29134 -10.7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,53001080089,3.186536901865369,22.710000000000001,30,101,96.879999999999995,30.410000000000000,12.710000000000001,0.300000000000000,56.409999999999997,0.180000000000000,0.000000000000000,1.277365421646900,100.000000000000000,0.000000000000000,95.640000000000001,4.230000000000000,0.080000000000000,0.030000000000000,0.000000000000000,0.030000000000000,4.070000000000000,0.620000000000000,44.939999999999998,50.229999999999997,0.080000000000000,0.000000000000000,0.050000000000000,0.000000000000000,99.969999999999999,0.000000000000000,0.030000000000000,0.000000000000000,98.370000000000005,1.110000000000000,0.520000000000000,4.200000000000000,79.430000000000007,15.800000000000001,0.140000000000000,0.080000000000000,0.190000000000000,0.000000000000000,0.160000000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000037125215130,0.029717233120341,0.114947991722667,0.000060037085301,95.090000000000003,1123.279999999999973,111.312303440388831,0.000000000000000,100.000000000000000,100.000000000000000,100.000000000000000,100.000000000000000,100.000000000000000,NaN,3149.617735287526102,7569.054889072691367,"POLYGON ((-48.01011 -15.78044, -48.01542 -15.7..."
12344,53001080090,2.815789473684211,14.020000000000000,26,96,89.250000000000000,17.449999999999999,11.529999999999999,0.000000000000000,71.030000000000001,0.000000000000000,0.000000000000000,2.599055443227950,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,2.900000000000000,0.000000000000000,1.450000000000000,88.409999999999997,5.800000000000000,0.000000000000000,1.450000000000000,0.000000000000000,89.859999999999999,2.900000000000000,7.250000000000000,0.000000000000000,91.299999999999997,5.800000000000000,2.900000000000000,95.650000000000006,1.450000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,2.900000000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000064994182514,0.030199098735347,0.115141811282508,0.000051950798235,78.260000000000005,1483.119999999999891,171.296296296296305,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,NaN,1988.238292009416682,2671.917043771586577,"POLYGON ((-47.66366 -15.64305, -47.66343 -15.6..."
12345,53001080094,2.991935483870968,18.520000000000000,25,111,93.159999999999997,24.530000000000001,23.719999999999999,0.270000000000000,51.210000000000001,0.270000000000000,0.000000000000000,-0.129648558890625,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.930000000000000,0.930000000000000,34.259999999999998,62.960000000000001,0.000000000000000,0.000000000000000,0.000000000000000,0.930000000000000,98.150000000000006,0.930000000000000,0.000000000000000,0.930000000000000,92.590000000000003,0.000000000000000,7.410000000000000,2.780000000000000,18.520000000000000,77.780000000000001,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.930000000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000065102582200,0.029591776551053,0.115005619492870,0.000060315440674,95.370000000000005,2242.559999999999945,230.303030303030283,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,NaN,2356.262461572796383,1886.939243531011243,"POLYGON ((-48.0398 -15.87807, -48.04002 -15.87..."
12346,53001080095,2.926470588235294,25.100000000000001,27,105,93.870000000000005,25.469999999999999,8.890000000000001,0.100000000000000,65.530000000000001,0.000000000000000,0.000000000000000,1.065393206436609,100.000000000000000,0.000000000000000,94.719999999999999,0.000000000000000,0.290000000000000,4.990000000000000,0.000000000000000,0.000000000000000,0.290000000000000,0.590000000000000,8.800000000000001,89.739999999999995,0.590000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,99.409999999999997,0.590000000000000,0.000000000000000,98.829999999999998,0.590000000000000,0.000000000000000,0.290000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.290000000000000,0.000000000000000,6.416914225024783,0.000000000000000,39.753132139665411,50.208664333526642,10.038203526807948,0.000000000000000,62.198742347815980,16.005125473218570,21.796132178965447,0.000008453422918,0.030349339927874,0.115278498127415,0.000059539555808,99.709999999999994,1687.150000000000091,57.335581787521079,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,17255.451816932829388,1408.288020310634238,8057.811878181278189,"POLYGON ((-47.86647 -15.59168, -47.86696 -15.5..."
12347,53001080096,3.133928571428572,47.439999999999998,32,96,97.439999999999998,33.329999999999998,10.830000000000000,0.000000000000000,55.840000000000003,0.000000000000000,0.000000000000000,-1.739138832075000,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,2.680000000000000,0.000000000000000,65.180000000000007,32.140000000000001,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,99.109999999999999,0.890000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,94.640000000000001,5.360000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000005768214069,0.029483562236572,0.115130013672384,0.000058122273245,100.000000000000000,4710.899999999999636,253.333333333333343,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,NaN,5860.596567147706992,522.414700045862219,"POLYGON ((-47.90935 -15.83957, -47.90952 -15.8..."

In [32]:
geodf = gpd.GeoDataFrame(final_table)
geodf.to_file('/Volumes/ssd/Doutorado/DATASET/classify_slums/slum_variables.shp')

/var/folders/5l/x3ysgz0n0mvd7msxlmn75zhw0000gp/T/ipykernel_75630/312484101.py:2: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  geodf.to_file('/Volumes/ssd/Doutorado/DATASET/classify_slums/slum_variables.shp')
/Users/joaosilva/workspace/phd/classify-slum/venv/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'no_wtr_pipe' to 'no_wtr_pip'
  ogr_write(